name: Main

on:
  workflow_dispatch:
  push:

env:
  BUILD_TYPE: ${{ inputs.build-type || 'release' }}
  APK_DIR: app/build/outputs/apk

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: set up JDK 21
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Generate version
        run: ./gradlew getVersion
      - name: Set environment variables
        run: |
          echo "VERSION=$(cat app/build/version.txt)" >> $GITHUB_ENV
          if [[ "${{ env.BUILD_TYPE }}" == 'debug' ]]; then
              echo "ASSEMBLE_TYPE=assembleDebug" >> "$GITHUB_ENV"
          else
              echo "ASSEMBLE_TYPE=assembleRelease" >> "$GITHUB_ENV"
          fi
      - name: Print env variables
        run: |
          echo 'BUILD_TYPE: ${{ env.BUILD_TYPE }}'
          echo 'ASSEMBLE_TYPE: ${{ env.ASSEMBLE_TYPE }}'
          echo 'VERSION: ${{ env.VERSION }}'
      - name: Build APK
        run: ./gradlew app:${{ env.ASSEMBLE_TYPE }}
      - name: Rename release apk
        if: ${{ env.BUILD_TYPE == 'release' }}
        run: mv ${{ env.APK_DIR }}/${{ env.BUILD_TYPE }}/app-release-unsigned.apk ${{ env.APK_DIR }}/${{ env.BUILD_TYPE }}/app-${{ env.BUILD_TYPE }}.apk

      - name: Rename
        run: mv ${{ env.APK_DIR }}/${{ env.BUILD_TYPE }}/app-${{ env.BUILD_TYPE }}.apk VolumeKeyMusicManagerModule-${{ env.BUILD_TYPE }}-${{ env.VERSION }}.apk
      - name: Upload
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: Build Artifacts
          path: VolumeKeyMusicManagerModule-${{ env.BUILD_TYPE }}-${{ env.VERSION }}.apk
