name: Publish Release

on: 
  - workflow_dispatch

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  publish-release:
    runs-on: ubuntu-latest
    needs: call-build 
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Build Artifacts    
      - name: Publish APK
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: VolumeKeyMusicManagerModule-release.apk
          automatic_release_tag: "latest"
